CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(10) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  otp VARCHAR(6),
  otp_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
